project: 
  type: website
  output-dir: docs

website:
  title: "Cassia Roth's Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/products/report/starter-analysis-report.qmd
          - text: "R Coding Exercise"
            file: coding-exercise/coding-exercise.qmd
          - text: "Presentation Exercise"
            file: presentation-exercise/presentation-exercise.qmd
          - text: "Tidy Tuesday Exercise"
            file: tidytuesday-exercise/tidytuesday-exercise.qmd
          - text: "Complex Data Exercise - Module 4"
            file: data-exercise/data-exercise.qmd
          - text: "CDC Data Exercise - Module 5"
            file: cdcdata-exercise/cdcdata-exercise.qmd
          - text: "Fitting Exercise - Module 8"
            file: fitting-exercise/fitting-exercise.qmd
          - text: "Machine Learning Exercise - Module 11"
            file: ml-models-exercise/ml-models-exercise.qmd
    right:
      - icon: github 
        href: https://github.com/cp-roth/cassiaroth-MADA-portfolio.git     

format:
  html:
    theme: lux
    highlight: zenburn
    css: styles.css
    toc: FALSE


